config/routes.rb
Rails.application.routes.draw do
  resources :offers

  root 'home#index'

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @offers = Offer.all
  end

  def show
    @offer = Offer.find(params[:id])
  end

  def new
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def create
    @offer = Offer.new(offer_params)
    if @offer.save
      redirect_to @offer
    else
      render 'new'
    end
  end

  def update
    @offer = Offer.find(params[:id])

    if @offer.update(offer_params)
      redirect_to @offer
    else
      render 'edit'
    end
  end

  private
  def offer_params
    params.require(:offer).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ClothingRack
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/offers/edit.html.haml
%h1 Editing Offer

= form_for :offer, url: offer_path(@offer), method: :patch do |f|
  - if @offer.errors.any?
    %div#error-explanation
      %h2
        = pluralize(@offer.errors.count, "error")
        prohibited this offer from being saved:
        %ul
          - @offer.errors.full_messages.each do |message|
            %li= message
  %p
    = f.label :title
    = f.text_field :title

  %p
    = f.label :description
    = f.text_area :description

  %p
    = f.submit

app/views/offers/index.html.haml
%table
  %thead
    %tr
      %th Title
      %th Description
      %th{colspan: 2}
  %tbody
    - @offers.each do |offer|
      %tr
        %td= offer.title
        %td= offer.description
        %td= link_to 'Show', offer_path(offer)
        %td= link_to 'Edit', edit_offer_path(offer)

app/views/offers/new.html.haml
%h1 New Offer

= form_for :offer, url: offers_path do |f|
  %p
    = f.label :title
    = f.text_field :title

  %p
    = f.label :description
    = f.text_area :description

  %p
    = f.submit

app/views/offers/show.html.haml
%p
  %strong Title:
  = @offer.title

%p
  %strong Text:
  = @offer.description

= link_to 'Back', offers_path
= link_to 'Edit', edit_offer_path(@offer)